stages:
- build
- test
- build-docker
#- test-docker
- release

variables:
  TEST_IMAGE: aksw/agdistis:$CI_BUILD_REF_NAME
  IMAGE: aksw/agdistis:latest

build:
  image: maven
  stage: build
  only:
    - master
  script:
    - mvn package -Dmaven.test.skip=true
  artifacts:
    paths:
    - target/*.war

test:
  image: maven
  stage: test
  only:
    - master
  script:
    - cp -r indextest index
    - mvn test

build-docker:
  image: docker:latest
  stage: build-docker
  services:
    - docker:dind
  only:
    - master
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASS
  script:
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

TODO: re-enable once we have small test index
test-docker:
  image: docker
  stage: test-docker
  only:
    - master
  services:
    - docker:dind
  script:
    - docker pull $TEST_IMAGE
    - docker run -d --name agdistis -v `pwd`/testindex:/usr/local/tomcat/index -v `pwd`/test-docker.sh:/usr/local/tomcat/test-docker.sh $TEST_IMAGE
    - sleep 30
    - docker exec agdistis sh /usr/local/tomcat/test-docker.sh

release:
  image: docker:latest
  stage: release
  services:
    - docker:dind
  only:
    - master
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASS
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $IMAGE
    - docker push $IMAGE
