stages:
- build
- test
- build-docker
- test-docker
- release

variables:
  TEST_IMAGE: aksw/agdistis:$CI_BUILD_REF_NAME
  IMAGE: aksw/agdistis:latest

build:
  image: maven
  stage: build
  only:
    - master
  script:
    - mvn package -Dmaven.test.skip=true
  artifacts:
    paths:
    - target/*.war

test:
  image: maven
  stage: test
  only:
    - master
  cache:
    key: "index"
    paths:
      - index/
  # download index if it's not cached yet
  before_script:
    - apt-get update &&
      apt-get install -y p7zip-full &&
      wget http://titan.informatik.uni-leipzig.de/rusbeck/agdistis/en/indexdbpedia_en_2014.7z &&
      7z x indexdbpedia_en_2014.7z &&
      mv indexdbpedia_en_2014 index
  script:
    - mvn test

build-docker:
  image: docker:latest
  stage: build-docker
  services:
    - docker:dind
  only:
    - master
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASS
  script:
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

test-docker:
  image: docker
  stage: test-docker
  only:
    - master
  services:
    - docker:dind
  cache:
    key: "index"
    paths:
      - index/
  script:
    - docker pull $TEST_IMAGE
    - docker run -d --name agdistis -v /cache/aksw/AGDISTIS/index:/usr/local/tomcat/index $TEST_IMAGE
    - sleep 30
    - ./test-docker.sh

release:
  image: docker:latest
  stage: release
  services:
    - docker:dind
  only:
    - master
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASS
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $IMAGE
    - docker push $IMAGE
