stages:
- test
- build
- build-docker
- test-docker
- release

variables:
  TEST_IMAGE: aksw/agdistis:$CI_BUILD_REF_NAME
  TEST_IMAGE_DICE: dicegroup/agdistis:$CI_BUILD_REF_NAME
  IMAGE: aksw/agdistis:latest
  IMAGE_DICE: dicegroup/agdistis:latest

test:
  image: maven
  stage: test
  only:
    - master
  script:
    - cp -r indextest index
    - mvn clean test

build:
  image: maven
  stage: build
  only:
    - master
  script:
    - mvn clean package -Dmaven.test.skip=true
  artifacts:
    paths:
    - target/*.war

build-docker:
  image: docker:latest
  stage: build-docker
  services:
    - docker:dind
  only:
    - master
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASS
  script:
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE
    - docker tag $TEST_IMAGE $TEST_IMAGE_DICE
    - docker push $TEST_IMAGE_DICE

test-docker:
  image: docker
  stage: test-docker
  only:
    - master
  services:
    - docker:dind
  script:
    - docker pull $TEST_IMAGE
    - docker run -d --name agdistis -v `pwd`/indextest:/usr/local/tomcat/index -v `pwd`/test-docker.sh:/usr/local/tomcat/test-docker.sh $TEST_IMAGE
    - sleep 30
    - docker exec agdistis sh /usr/local/tomcat/test-docker.sh

release:
  image: docker:latest
  stage: release
  services:
    - docker:dind
  only:
    - master
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASS
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $IMAGE
    - docker push $IMAGE
    - docker tag $TEST_IMAGE $IMAGE_DICE
    - docker push $IMAGE_DICE
